import { Company, Job } from "./types"

export const companies: Company[] = [
  {
    slug: "humain",
    name: "Humain",
    website: "https://humain.ai",
    linkedin: "https://www.linkedin.com/company/humainai",
    logo_url: "/logos/humain.svg",
    stage: "Growth",
    sector: ["AI Infrastructure"],
    city: "Riyadh",
    description: "PIF-backed AI investment company building AI infrastructure for Saudi Arabia. $23B in partnerships with NVIDIA.",
    careers_url: "https://humain.ai",
  },
  {
    slug: "sdaia",
    name: "SDAIA",
    website: "https://sdaia.gov.sa",
    linkedin: "https://www.linkedin.com/company/sdikiaia",
    logo_url: "/logos/sdaia.svg",
    stage: "Growth",
    sector: ["AI", "Government"],
    city: "Riyadh",
    description: "Saudi Data & AI Authority. Drives the national AI strategy and runs accelerator programs for AI startups.",
    careers_url: "https://sdaia.gov.sa/en/SDAIA/Pages/Careers.aspx",
  },
  {
    slug: "mozn",
    name: "Mozn",
    website: "https://mozn.ai",
    linkedin: "https://www.linkedin.com/company/mozn",
    logo_url: "/logos/mozn.png",
    stage: "Series A",
    sector: ["AI", "Fintech"],
    city: "Riyadh",
    description: "Enterprise AI for fraud detection and Arabic NLP. Built Focal (AML compliance) and OSOS (text intelligence).",
    careers_url: "https://www.mozn.ai/careers",
  },
  {
    slug: "intelmatix",
    name: "Intelmatix",
    website: "https://intelmatix.ai",
    linkedin: "https://www.linkedin.com/company/intelmatix",
    logo_url: "/logos/intelmatix.png",
    stage: "Series A",
    sector: ["AI", "Enterprise"],
    city: "Riyadh",
    description: "MIT-founded deep tech AI company. Largest AI Series A in MENA. AI-powered decision intelligence for enterprises.",
    careers_url: "https://intelmatix.ai/company-careers.html",
  },
  {
    slug: "lucidya",
    name: "Lucidya",
    website: "https://lucidya.com",
    linkedin: "https://www.linkedin.com/company/lucidya",
    logo_url: "/logos/lucidya.png",
    stage: "Series A",
    sector: ["AI", "SaaS"],
    city: "Riyadh",
    description: "AI-powered customer experience management platform. Leading CX SaaS in the Arab world. 4-day work week.",
    careers_url: "https://www.lucidya.com/careers-at-lucidya/",
  },
  {
    slug: "cognna",
    name: "Cognna",
    website: "https://www.cognna.com",
    linkedin: "https://www.linkedin.com/company/cognna",
    logo_url: "/logos/cognna.png",
    stage: "Series A",
    sector: ["AI", "Cybersecurity"],
    city: "Riyadh",
    description: "AI-powered cybersecurity platform providing advanced threat detection and SOC automation for enterprises.",
    careers_url: "https://www.cognna.com",
  },
  {
    slug: "deep-sa",
    name: "Deep SA",
    website: "https://deep.sa",
    linkedin: "https://www.linkedin.com/company/deepsa",
    logo_url: "/logos/deep-sa.png",
    stage: "Seed",
    sector: ["AI", "NLP"],
    city: "Riyadh",
    description: "Building localized AI solutions and strengthening Saudi Arabia's AI innovation landscape. $4.5M SAR pre-seed.",
    careers_url: "https://deep.sa",
  },
  {
    slug: "hazen",
    name: "Hazen.ai",
    website: "https://hazen.ai",
    linkedin: "https://www.linkedin.com/company/hazen-ai",
    logo_url: "/logos/hazen.png",
    stage: "Seed",
    sector: ["AI", "Smart Cities"],
    city: "Makkah",
    description: "AI computer vision for traffic management and road safety. Global leader in traffic AI innovation.",
    careers_url: "https://hazen.ai/careers",
  },
  {
    slug: "oqood",
    name: "Oqood",
    website: "https://oqood.ai",
    linkedin: "https://www.linkedin.com/company/oqood",
    logo_url: "/logos/oqood.svg",
    stage: "Seed",
    sector: ["AI", "Legaltech"],
    city: "Riyadh",
    description: "AI-powered legal technology. Automating legal workflows with intelligent document analysis. Sanabil-backed.",
    careers_url: "https://oqood.ai",
  },
  {
    slug: "sawt",
    name: "Sawt",
    website: "https://sawt.ai",
    linkedin: "https://www.linkedin.com/company/sawt-ai",
    logo_url: "/logos/sawt.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "STV AI Fund's first investment. Building AI-native products for the MENA region.",
    careers_url: "https://sawt.ai",
  },
  {
    slug: "unifonic",
    name: "Unifonic",
    website: "https://unifonic.com",
    linkedin: "https://www.linkedin.com/company/unifonic",
    logo_url: "/logos/unifonic.png",
    stage: "Series B",
    sector: ["AI", "CPaaS"],
    city: "Riyadh",
    description: "AI-powered customer engagement platform (CPaaS). 500+ employees, serving 5000+ companies across MENA.",
    careers_url: "https://jobs.unifonic.com",
  },
  {
    slug: "elm",
    name: "Elm",
    website: "https://elm.sa",
    linkedin: "https://www.linkedin.com/company/elm",
    logo_url: "/logos/elm.svg",
    stage: "Growth",
    sector: ["AI", "Govtech"],
    city: "Riyadh",
    description: "PIF-owned digital government services company. Building AI-powered e-services for Saudi government and financial sectors.",
    careers_url: "https://career.elm.sa/elm",
  },
  {
    slug: "governata",
    name: "Governata",
    website: "https://governata.com",
    linkedin: "https://www.linkedin.com/company/governata",
    logo_url: "/logos/governata.png",
    stage: "Seed",
    sector: ["AI", "Compliance"],
    city: "Riyadh",
    description: "AI-powered governance and compliance platform. Founded by ex-Foodics COO. $4M seed round, Jan 2026.",
    careers_url: "https://governata.com",
  },
  {
    slug: "dphish",
    name: "dPhish",
    website: "https://dphish.com",
    linkedin: "https://www.linkedin.com/company/dphish",
    logo_url: "/logos/dphish.png",
    stage: "Seed",
    sector: ["AI", "Cybersecurity"],
    city: "Riyadh",
    description: "AI-powered anti-phishing platform. Flat6Labs backed. Protecting organizations from social engineering attacks.",
    careers_url: "https://dphish.com",
  },
  {
    slug: "cyberni",
    name: "Cyberni",
    website: "https://cyberni.com",
    linkedin: "https://www.linkedin.com/company/cyberni",
    logo_url: "/logos/cyberni.png",
    stage: "Seed",
    sector: ["AI", "Cybersecurity"],
    city: "Riyadh",
    description: "AI-driven cybersecurity startup. Flat6Labs backed. Building intelligent security solutions for Saudi enterprises.",
    careers_url: "https://cyberni.com",
  },
  {
    slug: "calo",
    name: "Calo",
    website: "https://calo.app",
    linkedin: "https://www.linkedin.com/company/caborone",
    logo_url: "/logos/calo.png",
    stage: "Series A",
    sector: ["AI", "Healthtech"],
    city: "Riyadh",
    description: "AI-powered personalized meal planning and delivery. Uses machine learning to create custom nutrition plans.",
    careers_url: "https://calo.app",
  },
  {
    slug: "atam",
    name: "ATAM",
    website: "https://atam.careers",
    linkedin: "https://www.linkedin.com/company/atam",
    logo_url: "/logos/atam.svg",
    stage: "Seed",
    sector: ["AI", "Defense"],
    city: "Riyadh",
    description: "Autonomous defense systems and intelligence technology, built from Saudi Arabia. 19 open roles across engineering and operations.",
    careers_url: "https://atam.careers",
  },
  {
    slug: "solidrange",
    name: "Solidrange",
    website: "https://solidrange.com",
    linkedin: "https://www.linkedin.com/company/solidrange",
    logo_url: "/logos/solidrange.svg",
    stage: "Seed",
    sector: ["AI", "Cybersecurity"],
    city: "Riyadh",
    description: "AI-powered cybersecurity GRC automation. $2.4M seed round.",
    careers_url: "https://solidrange.com",
  },
  {
    slug: "kashon",
    name: "Kashon",
    website: "https://kashon.sa",
    linkedin: "https://www.linkedin.com/company/kashon",
    logo_url: "/logos/kashon.svg",
    stage: "Series A",
    sector: ["AI", "Energy"],
    city: "Riyadh",
    description: "AI operations platform for fuel stations. $16M Series A.",
    careers_url: "https://kashon.sa",
  },
  {
    slug: "safqah",
    name: "Safqah",
    website: "https://safqah.com",
    linkedin: "https://www.linkedin.com/company/safqah",
    logo_url: "/logos/safqah.svg",
    stage: "Seed",
    sector: ["AI", "Proptech"],
    city: "Riyadh",
    description: "AI credit assessment for real estate developers. $15.2M seed round.",
    careers_url: "https://safqah.com",
  },
  {
    slug: "sayfi",
    name: "SayFi",
    website: "https://sayfi.co",
    linkedin: "https://www.linkedin.com/company/sayfi",
    logo_url: "/logos/sayfi.svg",
    stage: "Series A",
    sector: ["AI", "Fintech"],
    city: "Riyadh",
    description: "AI expense management for finance teams. $20M Series A.",
    careers_url: "https://sayfi.co",
  },
  {
    slug: "rawaa",
    name: "Rawaa",
    website: "https://rawaa.com",
    linkedin: "https://www.linkedin.com/company/rawaa",
    logo_url: "/logos/rawaa.svg",
    stage: "Series B",
    sector: ["AI", "Retail"],
    city: "Riyadh",
    description: "Cloud POS with AI accounting for merchants. $45M Series B.",
    careers_url: "https://rawaa.com",
  },
  {
    slug: "nuwayra",
    name: "Nuwayra",
    website: "https://nuwayra.ai",
    linkedin: "https://www.linkedin.com/company/nuwayra",
    logo_url: "/logos/nuwayra.svg",
    stage: "Seed",
    sector: ["Generative AI"],
    city: "Riyadh",
    description: "Generative AI for government and enterprise. $2.1M pre-seed.",
    careers_url: "https://nuwayra.ai",
  },
  {
    slug: "ummar",
    name: "Ummar",
    website: "https://ummar.sa",
    linkedin: "https://www.linkedin.com/company/ummar",
    logo_url: "/logos/ummar.svg",
    stage: "Seed",
    sector: ["AI", "Proptech"],
    city: "Riyadh",
    description: "AI-powered rental and property management automation. $4M seed.",
    careers_url: "https://ummar.sa",
  },
  {
    slug: "merit-incentives",
    name: "Merit Incentives",
    website: "https://meritincentives.com",
    linkedin: "https://www.linkedin.com/company/meritincentives",
    logo_url: "/logos/merit.svg",
    stage: "Growth",
    sector: ["AI", "HR Tech"],
    city: "Riyadh",
    description: "Employee engagement and incentives tech. Acquired Australian company to expand globally.",
    careers_url: "https://meritincentives.com",
  },
  {
    slug: "judhur",
    name: "Judhur",
    website: "https://judhur.com",
    linkedin: "https://www.linkedin.com/company/judhur",
    logo_url: "/logos/judhur.svg",
    stage: "Seed",
    sector: ["AI", "E-commerce"],
    city: "Riyadh",
    description: "AI multi-channel e-commerce management for Amazon, Salla, Zid, and Noon. $500K pre-seed.",
    careers_url: "https://judhur.com",
  },
  {
    slug: "gbt",
    name: "GBT",
    website: "https://gbt.sa",
    linkedin: "https://www.linkedin.com/company/gbt-sa",
    logo_url: "/logos/gbt.svg",
    stage: "Seed",
    sector: ["AI", "Geospatial"],
    city: "Riyadh",
    description: "Geospatial AI and no-code spatial data tools. $1.33M pre-seed.",
    careers_url: "https://gbt.sa",
  },
  {
    slug: "jazer",
    name: "Jazer",
    website: "https://jazer.io",
    linkedin: "https://www.linkedin.com/company/jazer",
    logo_url: "/logos/jazer.svg",
    stage: "Seed",
    sector: ["AI", "E-commerce"],
    city: "Riyadh",
    description: "AI inventory and multi-platform e-commerce management. Pre-seed.",
    careers_url: "https://jazer.io",
  },
  {
    slug: "rukiza",
    name: "Rukiza",
    website: "https://rukiza.com",
    linkedin: "https://www.linkedin.com/company/rukiza",
    logo_url: "/logos/rukiza.svg",
    stage: "Seed",
    sector: ["AI", "SaaS"],
    city: "Riyadh",
    description: "SaaS for scheduling and blockchain document verification. $133K pre-seed.",
    careers_url: "https://rukiza.com",
  },
  {
    slug: "sdaia-hexagon",
    name: "SDAIA Hexagon",
    website: "https://hexagon.com",
    linkedin: "https://www.linkedin.com/company/hexagon",
    logo_url: "/logos/hexagon.svg",
    stage: "Growth",
    sector: ["AI Infrastructure"],
    city: "Riyadh",
    description: "World's largest government Tier IV data center. 480MW facility in Riyadh. SDAIA and Hexagon partnership.",
    careers_url: "https://hexagon.com/company/careers",
  },
  {
    slug: "cranl",
    name: "Cranl",
    website: "https://cranl.com",
    linkedin: "https://www.linkedin.com/company/cranl",
    logo_url: "/logos/cranl.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "Saudi AI startup building intelligent products.",
    careers_url: "https://cranl.com",
  },
  {
    slug: "infiniarc",
    name: "INFINIARC",
    website: "https://infiniarc.com",
    linkedin: "https://www.linkedin.com/company/infiniarc",
    logo_url: "/logos/infiniarc.svg",
    stage: "Growth",
    sector: ["AI Hardware"],
    city: "Riyadh",
    description: "100% Saudi company building high-performance AI hardware and servers. MOU with Intel for AI PCs, workstations, and servers in KSA.",
    careers_url: "https://infiniarc.com",
  },
  {
    slug: "wittify",
    name: "Wittify.ai",
    website: "https://wittify.ai",
    linkedin: "https://www.linkedin.com/company/wittify",
    logo_url: "/logos/wittify.svg",
    stage: "Seed",
    sector: ["AI", "CX"],
    city: "Riyadh",
    description: "AI agents for omnichannel customer touchpoints — mobile, web, CRM, call centers, and social media.",
    careers_url: "https://wittify.ai",
  },
  {
    slug: "rvin",
    name: "RVIN",
    website: "https://rvin.ai",
    linkedin: "https://www.linkedin.com/company/rvin",
    logo_url: "/logos/rvin.svg",
    stage: "Seed",
    sector: ["AI", "E-commerce"],
    city: "Riyadh",
    description: "AI virtual employees for e-commerce SMEs. Automating customer engagement and operations.",
    careers_url: "https://rvin.ai",
  },
  {
    slug: "widebot",
    name: "WideBot",
    website: "https://widebot.ai",
    linkedin: "https://www.linkedin.com/company/widebot",
    logo_url: "/logos/widebot.png",
    stage: "Series A",
    sector: ["AI", "Chatbots"],
    city: "Riyadh",
    description: "Arabic AI chatbot solutions for governments and enterprises. 350+ clients across 12 countries.",
    careers_url: "https://widebot.ai",
  },
  {
    slug: "allam",
    name: "Allam",
    website: "https://sdaia.gov.sa",
    linkedin: "https://www.linkedin.com/company/sdikiaia",
    logo_url: "/logos/allam.svg",
    stage: "Growth",
    sector: ["LLM", "NLP"],
    city: "Riyadh",
    description: "SDAIA's Arabic large language model. Saudi Arabia's answer to GPT — the best Arabic AI model.",
    careers_url: "https://sdaia.gov.sa/en/SDAIA/Pages/Careers.aspx",
  },
]

// Jobs archived — now linking directly to company career pages
export const jobs: Job[] = []

// Helper functions
export function getCompanyBySlug(slug: string): Company | undefined {
  return companies.find((c) => c.slug === slug)
}

export function getJobsByCompany(slug: string): Job[] {
  return jobs.filter((j) => j.company_slug === slug)
}

export function getUniqueValues(key: keyof Job): string[] {
  return [...new Set(jobs.map((j) => j[key] as string))].filter(Boolean).sort()
}

export const filterOptions = {
  sector: [...new Set(companies.flatMap((c) => c.sector))].sort(),
  city: [...new Set(companies.map((c) => c.city))].sort(),
  companyStage: ["Seed", "Series A", "Series B", "Growth"],
}
