import { Company, Job } from "./types"

export const companies: Company[] = [
  {
    slug: "humain",
    name: "Humain",
    website: "https://humain.ai",
    linkedin: "https://www.linkedin.com/company/humainai",
    logo_url: "/logos/humain.png",
    stage: "Growth",
    sector: ["AI"],
    city: "Riyadh",
    description: "PIF-backed AI investment company building AI infrastructure for Saudi Arabia. $23B in partnerships with NVIDIA.",
    careers_url: "https://www.linkedin.com/company/humainai/jobs",
  },
  {
    slug: "sdaia",
    name: "SDAIA",
    website: "https://sdaia.gov.sa",
    linkedin: "https://www.linkedin.com/company/sdikiaia",
    logo_url: "/logos/sdaia.png",
    stage: "Growth",
    sector: ["AI"],
    city: "Riyadh",
    description: "Saudi Data & AI Authority. Drives the national AI strategy and runs accelerator programs for AI startups.",
    careers_url: "https://sdaia.gov.sa/en/SDAIA/Pages/Careers.aspx",
  },
  {
    slug: "mozn",
    name: "Mozn",
    website: "https://mozn.ai",
    linkedin: "https://www.linkedin.com/company/mozn",
    logo_url: "/logos/mozn.png",
    stage: "Series A",
    sector: ["AI"],
    city: "Riyadh",
    description: "Enterprise AI for fraud detection and Arabic NLP. Built Focal (AML compliance) and OSOS (text intelligence).",
    careers_url: "https://www.mozn.ai/careers",
  },
  {
    slug: "intelmatix",
    name: "Intelmatix",
    website: "https://intelmatix.ai",
    linkedin: "https://www.linkedin.com/company/intelmatix",
    logo_url: "/logos/intelmatix.png",
    stage: "Series A",
    sector: ["AI"],
    city: "Riyadh",
    description: "MIT-founded deep tech AI company. Largest AI Series A in MENA. AI-powered decision intelligence for enterprises.",
    careers_url: "https://intelmatix.ai/company-careers.html",
  },
  {
    slug: "lucidya",
    name: "Lucidya",
    website: "https://lucidya.com",
    linkedin: "https://www.linkedin.com/company/lucidya",
    logo_url: "/logos/lucidya.png",
    stage: "Series A",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI-powered customer experience management platform. Leading CX SaaS in the Arab world. 4-day work week.",
    careers_url: "https://www.lucidya.com/careers-at-lucidya/",
  },
  {
    slug: "cognna",
    name: "Cognna",
    website: "https://www.cognna.com",
    linkedin: "https://www.linkedin.com/company/cognna",
    logo_url: "/logos/cognna.png",
    stage: "Series A",
    sector: ["AI", "Cybersecurity"],
    city: "Riyadh",
    description: "AI-powered cybersecurity platform providing advanced threat detection and SOC automation for enterprises.",
    careers_url: "https://www.cognna.com",
  },
  {
    slug: "deep-sa",
    name: "Deep SA",
    website: "https://deep.sa",
    linkedin: "https://www.linkedin.com/company/deepsa",
    logo_url: "/logos/deep-sa.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "Building localized AI solutions and strengthening Saudi Arabia's AI innovation landscape.",
    careers_url: "https://deep.sa",
  },
  {
    slug: "hazen",
    name: "Hazen.ai",
    website: "https://hazen.ai",
    linkedin: "https://www.linkedin.com/company/hazen-ai",
    logo_url: "/logos/hazen.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Makkah",
    description: "AI computer vision for traffic management and road safety. Global leader in traffic AI innovation.",
    careers_url: "https://hazen.ai/careers",
  },
  {
    slug: "oqood",
    name: "Oqood",
    website: "https://oqood.ai",
    linkedin: "https://www.linkedin.com/company/oqood",
    logo_url: "/logos/oqood.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI-powered legal technology. Automating legal workflows with intelligent document analysis. Sanabil-backed.",
    careers_url: "https://www.linkedin.com/company/oqood/jobs",
  },
  {
    slug: "sawt",
    name: "Sawt",
    website: "https://sawt.ai",
    linkedin: "https://www.linkedin.com/company/sawt-ai",
    logo_url: "/logos/sawt.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "STV AI Fund's first investment. Building AI-native products for the MENA region.",
    careers_url: "https://www.linkedin.com/company/sawt-ai/jobs",
  },
  {
    slug: "unifonic",
    name: "Unifonic",
    website: "https://unifonic.com",
    linkedin: "https://www.linkedin.com/company/unifonic",
    logo_url: "/logos/unifonic.png",
    stage: "Series B",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI-powered customer engagement platform (CPaaS). 500+ employees, serving 5000+ companies across MENA.",
    careers_url: "https://jobs.unifonic.com",
  },
  {
    slug: "elm",
    name: "Elm",
    website: "https://elm.sa",
    linkedin: "https://www.linkedin.com/company/elm",
    logo_url: "/logos/elm.png",
    stage: "Growth",
    sector: ["AI"],
    city: "Riyadh",
    description: "PIF-owned digital government services company. Building AI-powered e-services for Saudi government and financial sectors.",
    careers_url: "https://career.elm.sa/elm",
  },
  {
    slug: "governata",
    name: "Governata",
    website: "https://governata.com",
    linkedin: "https://www.linkedin.com/company/governata",
    logo_url: "/logos/governata.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI-powered governance and compliance platform. Founded by ex-Foodics COO. $4M seed round, Jan 2026.",
    careers_url: "https://www.linkedin.com/company/governata/jobs",
  },
  {
    slug: "dphish",
    name: "dPhish",
    website: "https://dphish.com",
    linkedin: "https://www.linkedin.com/company/dphish",
    logo_url: "/logos/dphish.png",
    stage: "Seed",
    sector: ["AI", "Cybersecurity"],
    city: "Riyadh",
    description: "AI-powered anti-phishing platform. Flat6Labs backed. Protecting organizations from social engineering attacks.",
    careers_url: "https://www.linkedin.com/company/dphish/jobs",
  },
  {
    slug: "cyberni",
    name: "Cyberni",
    website: "https://cyberni.com",
    linkedin: "https://www.linkedin.com/company/cyberni",
    logo_url: "/logos/cyberni.png",
    stage: "Seed",
    sector: ["AI", "Cybersecurity"],
    city: "Riyadh",
    description: "AI-driven cybersecurity startup. Flat6Labs backed. Building intelligent security solutions for Saudi enterprises.",
    careers_url: "https://www.linkedin.com/company/cyberni/jobs",
  },
  {
    slug: "calo",
    name: "Calo",
    website: "https://calo.app",
    linkedin: "https://www.linkedin.com/company/caborone",
    logo_url: "/logos/calo.png",
    stage: "Series A",
    sector: ["AI", "Healthtech"],
    city: "Riyadh",
    description: "AI-powered personalized meal planning and delivery. Uses machine learning to create custom nutrition plans.",
    careers_url: "https://www.linkedin.com/company/caborone/jobs",
  },
  {
    slug: "atam",
    name: "ATAM",
    website: "https://atam.careers",
    linkedin: "https://www.linkedin.com/company/atam",
    logo_url: "/logos/atam.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "Autonomous defense systems and intelligence technology, built from Saudi Arabia. 19 open roles across engineering and operations.",
    careers_url: "https://atam.careers",
  },
  {
    slug: "solidrange",
    name: "Solidrange",
    website: "https://solidrange.com",
    linkedin: "https://www.linkedin.com/company/solidrange",
    logo_url: "/logos/solidrange.png",
    stage: "Seed",
    sector: ["AI", "Cybersecurity"],
    city: "Riyadh",
    description: "AI-powered cybersecurity GRC automation. $2.4M seed round.",
    careers_url: "https://www.linkedin.com/company/solidrange/jobs",
  },
  {
    slug: "kashon",
    name: "Kashon",
    website: "https://kashon.sa",
    linkedin: "https://www.linkedin.com/company/kashon",
    logo_url: "/logos/kashon.png",
    stage: "Series A",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI operations platform for fuel stations. $16M Series A.",
    careers_url: "https://www.linkedin.com/company/kashon/jobs",
  },
  {
    slug: "safqah",
    name: "Safqah",
    website: "https://safqah.com",
    linkedin: "https://www.linkedin.com/company/safqah",
    logo_url: "/logos/safqah.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI credit assessment for real estate developers. $15.2M seed round.",
    careers_url: "https://www.linkedin.com/company/safqah/jobs",
  },
  {
    slug: "sayfi",
    name: "SayFi",
    website: "https://sayfi.co",
    linkedin: "https://www.linkedin.com/company/sayfi",
    logo_url: "/logos/sayfi.png",
    stage: "Series A",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI expense management for finance teams. $20M Series A.",
    careers_url: "https://www.linkedin.com/company/sayfi/jobs",
  },
  {
    slug: "rawaa",
    name: "Rawaa",
    website: "https://rawaa.com",
    linkedin: "https://www.linkedin.com/company/rawaa",
    logo_url: "/logos/rawaa.png",
    stage: "Series B",
    sector: ["AI"],
    city: "Riyadh",
    description: "Cloud POS with AI accounting for merchants. $45M Series B.",
    careers_url: "https://www.linkedin.com/company/rawaa/jobs",
  },
  {
    slug: "nuwayra",
    name: "Nuwayra",
    website: "https://nuwayra.ai",
    linkedin: "https://www.linkedin.com/company/nuwayra",
    logo_url: "/logos/nuwayra.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "Generative AI for government and enterprise. $2.1M pre-seed.",
    careers_url: "https://www.linkedin.com/company/nuwayra/jobs",
  },
  {
    slug: "ummar",
    name: "Ummar",
    website: "https://ummar.sa",
    linkedin: "https://www.linkedin.com/company/ummar",
    logo_url: "/logos/ummar.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI-powered rental and property management automation. $4M seed.",
    careers_url: "https://www.linkedin.com/company/ummar/jobs",
  },
  {
    slug: "merit-incentives",
    name: "Merit Incentives",
    website: "https://meritincentives.com",
    linkedin: "https://www.linkedin.com/company/meritincentives",
    logo_url: "/logos/merit.png",
    stage: "Growth",
    sector: ["AI"],
    city: "Riyadh",
    description: "Employee engagement and incentives tech. Acquired Australian company to expand globally.",
    careers_url: "https://www.linkedin.com/company/meritincentives/jobs",
  },
  {
    slug: "judhur",
    name: "Judhur",
    website: "https://judhur.com",
    linkedin: "https://www.linkedin.com/company/judhur",
    logo_url: "/logos/judhur.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI multi-channel e-commerce management for Amazon, Salla, Zid, and Noon. $500K pre-seed.",
    careers_url: "https://www.linkedin.com/company/judhur/jobs",
  },
  {
    slug: "gbt",
    name: "GBT",
    website: "https://gbt.sa",
    linkedin: "https://www.linkedin.com/company/gbt-sa",
    logo_url: "/logos/gbt.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "Geospatial AI and no-code spatial data tools. $1.33M pre-seed.",
    careers_url: "https://www.linkedin.com/company/gbt-sa/jobs",
  },
  {
    slug: "jazer",
    name: "Jazer",
    website: "https://jazer.io",
    linkedin: "https://www.linkedin.com/company/jazer",
    logo_url: "/logos/jazer.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "AI inventory and multi-platform e-commerce management. Pre-seed.",
    careers_url: "https://www.linkedin.com/company/jazer/jobs",
  },
  {
    slug: "rukiza",
    name: "Rukiza",
    website: "https://rukiza.com",
    linkedin: "https://www.linkedin.com/company/rukiza",
    logo_url: "/logos/rukiza.png",
    stage: "Seed",
    sector: ["AI"],
    city: "Riyadh",
    description: "SaaS for scheduling and blockchain document verification. $133K pre-seed.",
    careers_url: "https://www.linkedin.com/company/rukiza/jobs",
  },
  {
    slug: "sdaia-hexagon",
    name: "SDAIA Hexagon",
    website: "https://hexagon.com",
    linkedin: "https://www.linkedin.com/company/hexagon",
    logo_url: "/logos/hexagon.png",
    stage: "Growth",
    sector: ["AI"],
    city: "Riyadh",
    description: "World's largest government Tier IV data center. 480MW facility in Riyadh. SDAIA and Hexagon partnership.",
    careers_url: "https://hexagon.com/company/careers",
  },
]

// Jobs archived — now linking directly to company career pages
export const jobs: Job[] = [
  {
    id: "tam-1",
    company_slug: "tamara",
    title: "Data Engineering Manager",
    company: "Tamara",
    location: "Remote",
    job_type: "Full-time",
    experience_level: "Manager",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-2",
    company_slug: "tamara",
    title: "Employee Relations Associate",
    company: "Tamara",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-3",
    company_slug: "tamara",
    title: "Talent Development Associate",
    company: "Tamara",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-4",
    company_slug: "tamara",
    title: "Talent Acquisition Associate",
    company: "Tamara",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-5",
    company_slug: "tamara",
    title: "Treasury Operations Analyst",
    company: "Tamara",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-6",
    company_slug: "tamara",
    title: "B2B CRM Manager",
    company: "Tamara",
    location: "Remote",
    job_type: "Full-time",
    experience_level: "Manager",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-7",
    company_slug: "tamara",
    title: "Mobile Engineer (Flutter)",
    company: "Tamara",
    location: "Remote",
    job_type: "Full-time",
    experience_level: "Senior",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-8",
    company_slug: "tamara",
    title: "Channel Partnership Associate",
    company: "Tamara",
    location: "Remote",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-9",
    company_slug: "tamara",
    title: "Key Account Manager",
    company: "Tamara",
    location: "Remote",
    job_type: "Full-time",
    experience_level: "Senior",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "tam-10",
    company_slug: "tamara",
    title: "B2B Growth Associate",
    company: "Tamara",
    location: "Dubai",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "Fintech",
    apply_url: "https://job-boards.eu.greenhouse.io/tamara",
    posted_date: "2026-03-14",
    source: "greenhouse",
  },
  {
    id: "fdc-1",
    company_slug: "foodics",
    title: "Senior Cloud Platform Engineer",
    company: "Foodics",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Senior",
    sector: "B2B SaaS",
    apply_url: "https://apply.workable.com/foodics/",
    posted_date: "2026-03-14",
    source: "workable",
  },
  {
    id: "fdc-2",
    company_slug: "foodics",
    title: "Senior Data Analyst",
    company: "Foodics",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Senior",
    sector: "B2B SaaS",
    apply_url: "https://apply.workable.com/foodics/",
    posted_date: "2026-03-14",
    source: "workable",
  },
  {
    id: "fdc-3",
    company_slug: "foodics",
    title: "Senior People Operations Specialist",
    company: "Foodics",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Senior",
    sector: "B2B SaaS",
    apply_url: "https://apply.workable.com/foodics/",
    posted_date: "2026-03-14",
    source: "workable",
  },
  {
    id: "fdc-4",
    company_slug: "foodics",
    title: "Senior Backend Engineer",
    company: "Foodics",
    location: "Remote",
    job_type: "Full-time",
    experience_level: "Senior",
    sector: "B2B SaaS",
    apply_url: "https://apply.workable.com/foodics/",
    posted_date: "2026-03-14",
    source: "workable",
  },
  {
    id: "cog-1",
    company_slug: "cognna",
    title: "Senior Threat Detection Engineer",
    company: "Cognna",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Senior",
    sector: "Cybersecurity",
    apply_url: "https://www.cognna.com",
    posted_date: "2026-03-14",
    source: "bayt",
  },
  {
    id: "cog-2",
    company_slug: "cognna",
    title: "Threat Detection Engineer",
    company: "Cognna",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "Cybersecurity",
    apply_url: "https://www.cognna.com",
    posted_date: "2026-03-14",
    source: "linkedin",
  },
  {
    id: "sif-1",
    company_slug: "sifi",
    title: "Customer Success Associate",
    company: "SiFi",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Entry",
    sector: "Fintech",
    apply_url: "https://sifi.breezy.hr",
    posted_date: "2026-03-14",
    source: "breezy",
  },
  {
    id: "wkc-1",
    company_slug: "wakecap",
    title: "Pre-sales Engineer",
    company: "WakeCap",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "IoT",
    apply_url: "https://www.wakecap.com/recruitment",
    posted_date: "2026-03-14",
    source: "careers_page",
  },
  {
    id: "mdf-1",
    company_slug: "madfu",
    title: "Integration Specialist",
    company: "Madfu",
    location: "Riyadh",
    job_type: "Full-time",
    experience_level: "Mid",
    sector: "Fintech",
    apply_url: "https://www.linkedin.com/company/madfu-limited",
    posted_date: "2026-03-14",
    source: "linkedin",
  },
]

// Helper functions
export function getCompanyBySlug(slug: string): Company | undefined {
  return companies.find((c) => c.slug === slug)
}

export function getJobsByCompany(slug: string): Job[] {
  return jobs.filter((j) => j.company_slug === slug)
}

export function getUniqueValues(key: keyof Job): string[] {
  return [...new Set(jobs.map((j) => j[key] as string))].filter(Boolean).sort()
}

export const filterOptions = {
  sector: ["AI", "Cybersecurity", "Healthtech"],
  city: ["Riyadh", "Makkah"],
  companyStage: ["Seed", "Series A", "Series B", "Growth"],
}
